apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: go-grpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        ports:
        - containerPort: 50053
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "orderuser"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "orderdb"
        readinessProbe:
          httpGet:
            path: /health
            port: 50053
          initialDelaySeconds: 5
          periodSeconds: 10
